### ISSUE TITLE
Not compatible with babel-core/register 5.8 when update to 0.5.7

### ISSUE THREAD

**Issue by XuJinNet** [othiym23/async-listener#51]
i use "-r babel-core/register" (Babel 5.8.35) on develop, when update to 0.5.7 (continuation-local-storage use it), will get the error in event "unhandledRejection": promise.__asl_wrapper is not a function.

Unhandled Rejection at: Promise  Promise {
  _d: 
   { p: [Circular],
     c: [],
     a: [],
     s: 2,
     d: true,
     v: [TypeError: promise.__asl_wrapper is not a function],
     h: false,
     n: false },
  __asl_wrapper: [Function: proxyWrapper] }  reason:  [TypeError: promise.__asl_wrapper is not a function]
TypeError: promise.__asl_wrapper is not a function
    at Promise.proxyWrapper [as __asl_wrapper] (E:\My_Projects\Java\Work_Space_For_IDEA\ant\ant-manage-web\node_modules\async-listener\index.js:438:17)
    at E:\My_Projects\Java\Work_Space_For_IDEA\ant\ant-manage-web\node_modules\async-listener\index.js:450:32
    at run (E:\My_Projects\Java\Work_Space_For_IDEA\ant\ant-manage-web\node_modules\core-js\modules\es6.promise.js:104:47)
    at E:\My_Projects\Java\Work_Space_For_IDEA\ant\ant-manage-web\node_modules\core-js\modules\es6.promise.js:115:28
    at flush (E:\My_Projects\Java\Work_Space_For_IDEA\ant\ant-manage-web\node_modules\core-js\modules\$.microtask.js:19:5)
    at E:\My_Projects\Java\Work_Space_For_IDEA\ant\ant-manage-web\node_modules\async-listener\glue.js:188:31
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)

**Comment by hayes** [comment]
Could you provide more details on how to reproduce the issue? Using babel 5 and default transforms, I was not able to reproduce any issues.

**Comment by hayes** [comment]
without any way to reproduce the issue, I spent a lot of time today trying to guess at what could be causing the issue. I have an  untested theory, but if you have a chance, could you try testing this change: https://github.com/hayes/async-listener/commit/7f1d80cde6b8cbcbcd3145f74746cb447685f788 to see if it fixes the issue for you?

**Comment by XuJinNet** [comment]
Yes, this patch is available for me, Thank you ! ! ! !
Hopefully, we can upgrade to the newest version as soon as possible.

**Comment by hayes** [comment]
I'll try to get a PR up as soon as I can get a test for the issue

**Comment by seanpk** [comment]
This is affecting parsing of swagger specs on startup of [blueoak-server](https://github.com/BlueOakJS/blueoak-server) projects that also have a dependency on this library.

**Comment by Qard** [comment]
Okay, this should be fixed now, and released with async-listener@0.5.8. Let me know if you have any further issues. :smile_cat:

**Comment by XuJinNet** [comment]
Thank you ! ! ! ! @Qard @hayes

**Comment by seanpk** [comment]
Thanks @Qard @hayes - it looks like things are back in order.

**Comment by beeman** [comment]
Thanks @hayes, that patch fixed my issue too :)
